GET http://localhost:3000/tax-position?date=2024-02-23T00:00:00Z HTTP/1.1

###

POST http://localhost:3000/transactions HTTP/1.1
content-type: application/json

{
	"eventType": "SALES",
	"date": "2024-02-22T17:29:39Z",
    "invoiceId": "3419027d-960f-4e8f-b8b7-f7b2b4791825",
  	"items": [{
        "itemId": "02db47b6-fe68-4005-a827-24c6e962f3dg",
        "cost": 1099, 
        "taxRate": 0.2
        }
    ]
}

###

POST http://localhost:3000/transactions HTTP/1.1
content-type: application/json

{
	"eventType": "TAX_PAYMENT",
	"date": "2024-02-22T17:29:39Z",
	"amount": 74901
}

###

PATCH http://localhost:3000/sale HTTP/1.1
content-type: application/json

{
    "date": "2024-02-22T17:29:39Z",
    "invoiceId": "3419027d-960f-4e8f-b8b7-f7b2b4791824",
    "itemId": "02db47b6-fe68-4005-a827-24c6e962f3df",
	"cost": 798,
 	"taxRate": 0.15
}
